### ISSUE TITLE
Erases pdfpc file on rebuild

### ISSUE THREAD

**Issue by rpglover64** [cebe/pdfpc-latex-notes#10]
Ideally, customizations in the pdfpc file would be kept around.

**Comment by cebe** [comment]
that would mean you need to detect changes and merge them back into the LaTeX source. Sounds quite impossible to me.

**Comment by rpglover64** [comment]
I don't mean merge the notes section. I mean don't erase e.g. the timer section.

**Comment by cebe** [comment]
can you elaborate a bit more? what is "timer section"?

**Comment by rpglover64** [comment]
If I launch `pdfpc` with `-d 20`, it adds 
```
[duration]
20
```
to the config file. Now, if I launch it without `-d 20`, it still remembers that I'm on a 20 minute timer. If I rebuild my document using `pdfpc-latex-notes`, this information is erased from the config file. Since `[notes]` is required to be the last section of the file, `pdfpc-latex-notes` could search for the section and start writing there (or at the end of the file if the section isn't found) rather than overwriting the whole file.

**Comment by cebe** [comment]
Interesting, seems behavior of pdfpc has changed since I created `pdfpc-latex-notes`. Will consider this.

**Comment by cebe** [comment]
as of #11 you can now specify the options inside the package so overwriting should not be a problem.
