### ISSUE TITLE
Notes associated to wrong frames.

### ISSUE THREAD

**Issue by gvgramazio** [cebe/pdfpc-latex-notes#25]
I don't know why this happens. I don't have the time right now to take a look at the problem (I should discuss my thesis in two days), but I will in this holidays. The problem is that in my presentation each pnote is shown with an offset of 1 frame (e.g. the note associated with the frame 4 is shown at frame 3).

I don't know why this happens, probably because I use the metropolis template, probably because I use a title page. Both of them could mess with the frame number.

This is also related to issue #21. Note that my solution is as simple as possible but tested only in my use case.

The solution is simply to reset the counter to a different value:

    \setcounter{framenumber}{1}

**Comment by gvgramazio** [comment]
My solution was simply wrong. Refer to issue #21 for a good solution. At least for now.

**Comment by cebe** [comment]
yeah well, if framenumber does not match the page number, weird things are happening...

Could you provide a small example presentation that reproduces the issue so I can play with it?

Good luck with the thesis btw :)

**Comment by gvgramazio** [comment]
I had so many things wrong that saying that I had an example is too much.

My problem was that the framenumber didn't match with the page number. The reason was simple and stupid: I used `\maketitle` without being in a frame. Surprisingly, there was no error. The only problem was that your package misplaced the labels.

My solution was simply wrong but I don't know why. If I use any command for setting the framenumber counter like `\setcounter`, `\stepcounter`, `\addtocounter` the counter is changed accordingly but all pnotes up to that framenumber are not shown and all the other ones are shown together. 

The workaround shown in issue #21 works well in my case if I keep `\maketitle` outside of a frame and there is no need for it if I simply put `\maketitle` inside a frame.

P.S. The presentation went well.

**Comment by cebe** [comment]
Okay, thanks for the feedback, I think the problem is similar enough to #21, so I keep this one closed.
